// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Todo struct {
	ID          int64         `json:"id"`
	UserID      sql.NullInt64 `json:"user_id"`
	ContentText string        `json:"content_text"`
	Done        bool          `json:"done"`
}

type UserDatum struct {
	ID           int64  `json:"id"`
	UserName     string `json:"user_name"`
	UserPassword string `json:"user_password"`
}
