# Code generated by sqlc. DO NOT EDIT.


import dataclasses




@dataclasses.dataclass()
class Todo:
    id: int
    user_id: int
    content_text: str
    done: bool



@dataclasses.dataclass()
class UserDatum:
    id: int
    user_name: str
    user_password: str


